pipeline {
    agent any
    stages {
        stage ('Build Servlet Project') {
            steps {
              sh  '/usr/lib/maven/bin/mvn clean package'
            }

            post {
                success{
                    echo 'Now Archiving ....'

                    archiveArtifacts artifacts : '**/*.war'
                }
            }
        }

    }
    
}
